#!/bin/bash

echo "=> install manifest-tool"
URL=https://github.com/estesp/manifest-tool/releases/download/v0.6.0/manifest-tool-linux-amd64

curl -sLo ./manifest-tool ${URL}
chmod +x ./manifest-tool

:<<EOM
echo "=> push multiarch"
ARCH="linux/arm,linux/amd64"
./manifest-tool push from-args \
--platforms ${ARCH} \
--template ${DOCKER_REPO}:ARCH \
--target ${DOCKER_REPO}:latest
EOM

echo "=> push multiarch"
./manifest-tool push from-spec manifest.yml


VERSION="$(docker container run --rm -it ${DOCKER_REPO}:latest -version | cut -d ' ' -f 2 | tr -d '\r')"

docker tag "${DOCKER_REPO}:latest" "${DOCKER_REPO}:${VERSION}"

docker push "${DOCKER_REPO}:${VERSION}"



