#!/bin/bash

IMAGE="firecyberice/caddy"
VERSION="$(docker container run --rm -it ${IMAGE}:latest -version | cut -d ' ' -f 2 | tr -d '\r')"

docker tag "${IMAGE}:latest" "${IMAGE}:${VERSION}"

docker push "${IMAGE}:${VERSION}"



